# Generated by Django 2.0.7 on 2019-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Keywords', models.TextField()),
                ('Author', models.TextField()),
                ('Description', models.TextField()),
                ('FiledOfStudies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meagazines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Keywords', models.TextField()),
                ('Author', models.TextField()),
                ('Description', models.TextField()),
                ('FiledOfStudies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Keywords', models.TextField()),
                ('Author', models.TextField()),
                ('Description', models.TextField()),
                ('FiledOfStudies', models.TextField()),
            ],
        ),
    ]
