# Generated by Django 2.0.7 on 2019-09-20 09:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='search_vector_Books',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='meagazines',
            name='search_vector_Magazines',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='search_vector_Thesis',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='books',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_Books'], name='engine_book_search__ff0b33_gin'),
        ),
        migrations.AddIndex(
            model_name='meagazines',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_Magazines'], name='engine_meag_search__d103cb_gin'),
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_Thesis'], name='engine_thes_search__8d8397_gin'),
        ),
    ]
