# Generated by Django 2.0.7 on 2019-09-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20190920_1522'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='books',
            name='engine_book_search__ff0b33_gin',
        ),
        migrations.RemoveIndex(
            model_name='meagazines',
            name='engine_meag_search__d103cb_gin',
        ),
        migrations.RemoveIndex(
            model_name='thesis',
            name='engine_thes_search__8d8397_gin',
        ),
        migrations.RemoveField(
            model_name='books',
            name='search_vector_Books',
        ),
    ]
