# Generated by Django 2.0.7 on 2019-09-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20190920_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meagazines',
            name='search_vector_Magazines',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='search_vector_Thesis',
        ),
    ]
